# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ching Wang
tagline: Junior Fullstack Software Engineer
description: Blog of Ching Wang, a Fullstack Software Engineer based in London.
  React, JavaScript, Ruby, Rails, Python, Flask, Jest, SASS / CSS, postgreSQL.
url: https://www.ching-wang.io/
Author: Ching Wang
image: "https://avatars3.githubusercontent.com/u/16280680?s=400&u=ed9f1f681a58778ddce479b9b059d03c057b9019&v=4"
lang: en_GB
twitter:
  username: ching_wang_io
  card: summary
show_excerpts: true

sass:
  sass_dir: _sass
  style: compressed

# Build settings

plugins:
  - jekyll-seo-tag
  # - jekyll-feed

highlighter: rouge
fenced_code_blocks: true

remote_theme: thelehhman/texture
theme: texture

permalink: /posts/:title/
texture:
  title: Ching Wang
  tagline: Full Stack Software Engineer
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: true

  social_links:
    github: ching-wang
    linkedIn: ching-wang # format: locale/username
    twitter: ching_wang_io
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
