name: Build and Deploy

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
          gem install bundler jekyll
          bundler install
      - name: Build
        run: bundle exec jekyll build
      - name: Deploy to S3
        if: github.ref == 'refs/heads/master'
        run: aws s3 sync _site/ s3://www.ching-wang.io/ --delete --acl=public-read && aws cloudfront create-invalidation --distribution-id=E1LDUE0LJJZIO9 --paths='/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
